version: '3.0'

services:
            
  configurationservice:
    build: ./
    container_name: configurationservice
    ports:
      - '8888:8080'
      
  discoveryservice:
    image: aista/eureka
    container_name: discoveryservice
    ports:
      - '8761:8761'
    environment:
      - 'eviction-interval-timer-in-ms: 1000'
