spring:
  profiles: dev
  cloud:
    config:
      discovery:
        enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/AITestingOrg/configuration-repository/
          searchPaths: edgeservice, userservice, tripmanagementcmd, tripmanagementquery, passenger, passenger, drivermanagementcmd, drivermanagementquery, discoveryservice, billingcmd, billingquery, paymentcmd, paymentquery, gmapsadapter, calculationservice 
server:
  port: 8080
  
#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.aitesting.microservices: DEBUG

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
        defaultZone: http://discoveryservice:8761/eureka/
        
---
spring:
  profiles: test
  cloud:
    config:
      enabled: true
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/AITestingOrg/configuration-repository/
          searchPaths: edgeservice, userservice, tripmanagementcmd, tripmanagementquery, passenger, passenger, drivermanagementcmd, drivermanagementquery, discoveryservice, billingcmd, billingquery, paymentcmd, paymentquery, gmapsadapter, calculationservice
          
          
management:
  security.enabled: false
  endpoints.web.exposure.include: "*"

server:
  port: 8080
  
#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    org.aitesting.microservices: DEBUG

