
spring.database.driverClassName: "org.postgresql.Driver"

spring:
  datasource:
    platform:  "postgres"
    url: "jdbc:postgresql://postgres:5432/eagle_eye_local"
    username: "postgres"
    password: "p0stgr@s"
    testWhileIdle: "true"
    validationQuery: "SELECT 1"
    
spring:
  jpa:
    database: "POSTGRESQL"
    show-sql: "true"
    properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"

security:
  oauth2:
   resource:
      userInfoUri: http://discovery-service:8901/auth/user

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/